name: Test and lint

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
        # make depends on poetry
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - name: Run linter
        run: |
          make lint
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # we want to test our package on several versions of Python
        python-version: ["3.8","3.9","3.10"]
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
        # make depends on poetry
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - name: test
        run: |
          poetry run pytest
  coverage:
    runs-on: ubuntu-latest
    needs: [tests]
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
        # make depends on poetry
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - name: run tests and instrument coverage
        run: make coverage
      - name: publish code coverage to code-climate
        uses: paambaati/codeclimate-action@v6.0.0
        env:
          CC_TEST_REPORTER_ID: d225929781d603a434587caa7e10c0e7927ad772fb5eb44b744dc2a0957b64f2
        with:
          coverageCommand: make coverage
          coverageLocations: |
            ${{github.workspace}}/*.lcov:lcov
          debug: true
