name: Test and lint

on:
  - push
  - pull_request

jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # we want to test our package on several versions of Python
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
        # make depends on poetry
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - name: Run linter and pytest
        run: |
          make check
      - name: run tests and instrument coverage
        run: make coverage
      - name: publish code coverage to code-climate
        uses: paambaati/codeclimate-action@v6.0.0
        env:
          CC_TEST_REPORTER_ID: d225929781d603a434587caa7e10c0e7927ad772fb5eb44b744dc2a0957b64f2
        with:
          debug: true
          coverageCommand: make coverage